from django.db import models


# Your models here
class Services(models.Model):
	business_intro = models.TextField(max_length=500)
	business_event_list1 = models.CharField(max_length=30)
	business_event_list2 = models.CharField(max_length=30)
	business_event_list3 = models.CharField(max_length=30)
	business_event_list4 = models.CharField(max_length=30)
	business_event_list5 = models.CharField(max_length=30)
	business_event_list6 = models.CharField(max_length=30)
	family_intro = models.TextField(max_length=500)
	family_event_list1 = models.CharField(max_length=30)
	family_event_list2 = models.CharField(max_length=30)
	family_event_list3 = models.CharField(max_length=30)
	family_event_list4 = models.CharField(max_length=30)
	family_event_list5 = models.CharField(max_length=30)
	family_event_list6 = models.CharField(max_length=30)
	charity_intro = models.TextField(max_length=500)
	charity_event_list1 = models.CharField(max_length=30)
	charity_event_list2 = models.CharField(max_length=30)
	charity_event_list3 = models.CharField(max_length=30)
	charity_event_list4 = models.CharField(max_length=30)
	charity_event_list5 = models.CharField(max_length=30)
	charity_event_list6 = models.CharField(max_length=30)
	cultural_intro = models.TextField(max_length=500)
	cultural_event_list1 = models.CharField(max_length=30)
	cultural_event_list2 = models.CharField(max_length=30)
	cultural_event_list3 = models.CharField(max_length=30)
	cultural_event_list4 = models.CharField(max_length=30)
	seminar_intro = models.TextField(max_length=500)
	seminar_event_list1 = models.CharField(max_length=30)
	seminar_event_list2 = models.CharField(max_length=30)
	seminar_event_list3 = models.CharField(max_length=30)
	seminar_event_list4 = models.CharField(max_length=30)
	seminar_event_list5 = models.CharField(max_length=30)
