# Generated by Django 3.2.5 on 2021-07-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('header_info', models.TextField(max_length=500)),
                ('about_intro', models.TextField(max_length=200)),
                ('job_title', models.CharField(max_length=50)),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_intro', models.TextField(max_length=400)),
                ('pro_img', models.ImageField(upload_to='pro_images')),
                ('home_family_img', models.ImageField(upload_to='event_images')),
                ('home_business_img', models.ImageField(upload_to='event_images')),
                ('home_cultural_img', models.ImageField(upload_to='event_images')),
                ('home_charity_img', models.ImageField(upload_to='event_images')),
                ('home_seminar_img', models.ImageField(upload_to='event_images')),
            ],
        ),
    ]
