# Generated by Django 3.2.5 on 2021-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0002_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='pro_img',
        ),
        migrations.AddField(
            model_name='home',
            name='pro_img1',
            field=models.ImageField(default='', upload_to='pro_images'),
        ),
        migrations.AddField(
            model_name='home',
            name='pro_img2',
            field=models.ImageField(default='', upload_to='pro_images'),
        ),
        migrations.AddField(
            model_name='home',
            name='pro_img3',
            field=models.ImageField(default='', upload_to='pro_images'),
        ),
    ]
