# Generated by Django 3.2.5 on 2021-07-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0005_auto_20210706_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(max_length=500)),
                ('mission_bold', models.TextField(max_length=300)),
                ('vision', models.TextField(max_length=500)),
                ('vision_bold', models.TextField(max_length=300)),
                ('testimonial1', models.TextField(max_length=800)),
                ('testimonial2', models.TextField(max_length=800)),
                ('testimonial3', models.TextField(max_length=800)),
                ('testimonial4', models.TextField(max_length=800)),
                ('client_name1', models.CharField(max_length=100)),
                ('client_name2', models.CharField(max_length=100)),
                ('client_name3', models.CharField(max_length=100)),
                ('client_name4', models.CharField(max_length=100)),
            ],
        ),
    ]
