# Generated by Django 3.2.5 on 2021-07-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0006_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='pro_first_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='pro_intro',
        ),
        migrations.RemoveField(
            model_name='home',
            name='pro_last_name',
        ),
        migrations.AddField(
            model_name='home',
            name='pro_first_name1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='pro_first_name2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='pro_first_name3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='pro_intro1',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='home',
            name='pro_intro2',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='home',
            name='pro_intro3',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='home',
            name='pro_last_name1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='pro_last_name2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='pro_last_name3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
