# Generated by Django 3.2.5 on 2021-07-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0007_auto_20210709_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='job_title',
        ),
        migrations.AddField(
            model_name='home',
            name='job_title1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='job_title2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='job_title3',
            field=models.CharField(default='', max_length=50),
        ),
    ]
