# Generated by Django 3.2.5 on 2021-07-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0008_auto_20210709_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='company_logo',
            field=models.ImageField(default='', upload_to='logo'),
        ),
    ]
