# Generated by Django 3.2.5 on 2021-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0010_alter_home_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='company_logo',
            field=models.ImageField(default='', upload_to='logo'),
        ),
    ]
