# Generated by Django 3.2.5 on 2021-07-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0011_alter_home_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='logo')),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('phone_code', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='company_logo',
        ),
    ]
