# Generated by Django 3.2.5 on 2021-07-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0012_auto_20210709_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeadFoot',
        ),
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='company_logo',
            field=models.ImageField(default='', upload_to='logo'),
        ),
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='home',
            name='phone_code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
