# Generated by Django 3.2.5 on 2021-07-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0014_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='cultural_event_list5',
        ),
        migrations.RemoveField(
            model_name='services',
            name='cultural_event_list6',
        ),
        migrations.RemoveField(
            model_name='services',
            name='seminar_event_list6',
        ),
    ]
